### ISSUE TITLE
Error when search many times changing parameters

### ISSUE THREAD

**Issue by dhaern** [MicFenne/BinanceNFT#1]
First search is working fine but if I search more times pressing the button more times I get this error:

![image](https://user-images.githubusercontent.com/7317522/129260008-2a441e9d-3efe-4cc1-86db-bd5e0d38708f.png)

**Error: Invalid attempt to spread non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method.**

I think it's related to line 271 in App.js: 

![image](https://user-images.githubusercontent.com/7317522/129260258-b95c1795-c0b9-4ba6-aa9b-78ec51300a6b.png)

**"const rows = data.data.items.map((row) => {"**

Tested with both development build and production.

**Comment by MicFenne** [comment]
https://github.com/MicFenne/BinanceNFT/commit/a51cb45367e97d9ded5721ef981a1ff35f2d645e
