### ISSUE TITLE
Error searching NFTs without filter

### ISSUE THREAD

**Issue by dhaern** [MicFenne/BinanceNFT#2]
I get error POST 400 when I search all NFTs without write an specific name (empty box).

![image](https://user-images.githubusercontent.com/7317522/129261014-55141257-905c-4bd3-b0b1-6c5d19c44426.png)

**Comment by MicFenne** [comment]
https://github.com/MicFenne/BinanceNFT/commit/a51cb45367e97d9ded5721ef981a1ff35f2d645e
